### ISSUE TITLE
changing text in start_demo node doesn't change text in on the website UI

### ISSUE THREAD

**Issue by LifeScribe** [sjoynt/mycarwash#1]
In the  #start_demo node, I changed the response text to read: 

"Thanks for using MyCarWash today $name!" and then in a second response added "We'd love to know what you think of our service. Would you be open to answering 2-3 short questions about the service experience?" 

However, when I go to the webUI, this change hasn't taken affect and still shows the former response:

> "Thank you for using one of our MyCarWash services. Your feedback is important to us. How would you rate your overall experience with us?"

Have tried in chrome and opera with private browsing turned on, but doesn't seem to change

**Comment by sjoynt** [comment]
Because it's a static message on the web UI, I've added, "Thanks for using MyCarWash!! We'd love to know what you think of our service. Would you be open to answering 2-3 short questions about the service experience?" 

Is this acceptable for now, I'll add an on-load class to the UI in release v2.

**Comment by LifeScribe** [comment]
@sjoynt could we change the text so it just includes "Thanks for using MyCarWash!! We'd love to know what you think of our service."

For readability (it would show up in a separate text bubble), what we can then do is jump to the welcome node where we'll have "Would you mind answering 2-3 questions about your service experience?"

**Comment by sjoynt** [comment]
I've written an onload() function and it will load the "start demo" node in assistant. Pushing the update tonight.

**Comment by LifeScribe** [comment]
Awesome thanks! I’m going back into the dialog tomorrow to see if i can get the probe nodes sorted. Read through the docs today- think i understand 

-Jeff Dyck
