### ISSUE TITLE
Web UI chat bubble not displaying start_demo hard coded message

### ISSUE THREAD

**Issue by LifeScribe** [sjoynt/mycarwash#2]
![screen shot 2018-11-28 at 3 35 11 pm](https://user-images.githubusercontent.com/1695628/49183767-59280500-f323-11e8-8076-7797a452fced.png)

**Comment by sjoynt** [comment]
The issue was the jump to node, you had it set for the condition utterance == "welcome", it would never evaluate to that because the utterance is start node. I changed that and made a welcome default to test on the website.
